#!/usr/bin/env python3
"""Generate speech/*.wav + speech/clips.js from tools/phrases.json using Piper
(neural TTS, en_US-lessac-medium). Usage:
  pip install piper-tts
  python3 tools/gen_speech.py /path/to/en_US-lessac-medium.onnx
Re-run after changing any spoken text; run `node tools/collect_phrases.js` first."""
import hashlib, json, sys, wave, os
from piper import PiperVoice

root = os.path.join(os.path.dirname(__file__), "..")
model = sys.argv[1] if len(sys.argv) > 1 else "en_US-lessac-medium.onnx"
phrases = json.load(open(os.path.join(root, "tools", "phrases.json")))
voice = PiperVoice.load(model)
os.makedirs(os.path.join(root, "speech"), exist_ok=True)
clips = {}
for text in phrases:
    name = hashlib.sha1(text.encode()).hexdigest()[:10] + ".wav"
    path = os.path.join(root, "speech", name)
    with wave.open(path, "wb") as w:
        voice.synthesize_wav(text, w)
    clips[text] = "speech/" + name
    print(f"{os.path.getsize(path)//1024:4d} KB  {text}")
with open(os.path.join(root, "speech", "clips.js"), "w") as f:
    f.write("// generated by tools/gen_speech.py — do not edit\nwindow.SPEECH_CLIPS = " + json.dumps(clips, indent=1, ensure_ascii=False) + ";\n")
print("total", sum(os.path.getsize(os.path.join(root, "speech", n)) for n in os.listdir(os.path.join(root, "speech")) if n.endswith(".wav")) // 1024, "KB")
